import { prisma } from "../lib/prisma";
import { getAllPermissions } from "../lib/permissions";
import fs from "fs";
import path from "path";

async function seedPermissions() {
  console.log("🌱 Seeding permissions from manifest...");

  const perms = getAllPermissions();

  for (const name of perms) {
    try {
      const existing = await prisma.permission.findUnique({ where: { name } });
      if (!existing) {
        await prisma.permission.create({ data: { name } });
        console.log(`  ➕ Created permission: ${name}`);
      }
    } catch (err) {
      console.error(`Failed to upsert permission ${name}:`, err);
    }
  }

  // Export manifest to frontend for type-safety / usage
  try {
    // Path to frontend repo (assumes frontend is sibling of backend)
    const frontendPath = path.resolve(
      __dirname,
      "..",
      "..",
      "..",
      "frontend",
      "src",
      "lib"
    );
    if (!fs.existsSync(frontendPath)) {
      console.warn(
        "Frontend path not found, skipping manifest export:",
        frontendPath
      );
    } else {
      const allJson = JSON.stringify(perms, null, 2);
      fs.writeFileSync(
        path.join(frontendPath, "generated-permissions.json"),
        allJson,
        "utf8"
      );

      const tsContent = `// AUTO-GENERATED FILE - DO NOT EDIT\n// Generated by seed-permissions.ts\nexport const ALL_PERMISSIONS = ${allJson} as const;\nexport type Permission = (typeof ALL_PERMISSIONS)[number];\n`;
      fs.writeFileSync(
        path.join(frontendPath, "generated-permissions.ts"),
        tsContent,
        "utf8"
      );
      console.log(
        "  ➕ Exported permissions to frontend/src/lib/generated-permissions.(json|ts)"
      );
    }
  } catch (err) {
    console.error("Failed to export manifest to frontend:", err);
  }

  console.log("🌱 Permission seeding completed.");
}

seedPermissions()
  .catch((e) => {
    console.error("❌ Permission seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
